# **importiing the dependicies**


In [ ]:
import numpy as np
import pandas as pd
import difflib  #to find the name of the movie closest to the name given by user
from sklearn.feature_extraction.text import TfidfVectorizer   #convert text data into feature vectors
from sklearn.metrics.pairwise import cosine_similarity # to find the item which is most similar

# **Data** **Preprocessing**

In [ ]:
movies = pd.read_csv('/content/movies.csv')


In [ ]:
#printing first five rows
movies.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
print(movies.shape)
movies.columns

(4803, 24)


Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [ ]:
#selecting relevent columns/features
selected_features = ['genres','keywords', 'production_companies','cast', 'director', 'tagline']
print(selected_features)

['genres', 'keywords', 'production_companies', 'cast', 'director', 'tagline']


In [ ]:
# replacing null values with null string
for feature in selected_features:
  movies[feature] = movies[feature].fillna('')

In [ ]:
# combining all selected features
combined_features = movies['genres']+''+movies['keywords']+''+movies['production_companies']+''+movies['cast']+''+movies['director']+''+movies['tagline']
print(combined_features)

In [ ]:
# converting the text data into numerical data
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 24496)	0.18114994667477258
  (0, 24062)	0.07190938618087739
  (0, 33750)	0.10426734785938684
  (0, 30523)	0.05984409106865187
  (0, 8763)	0.23269922271152288
  (0, 26813)	0.23269922271152288
  (0, 22415)	0.13098795552485595
  (0, 20030)	0.19597477748251127
  (0, 29569)	0.1349767942948084
  (0, 33074)	0.1657899241796345
  (0, 28682)	0.1679987936784005
  (0, 27562)	0.18311314744996285
  (0, 34196)	0.16475092483545706
  (0, 33761)	0.19951216928927837
  (0, 27606)	0.130146897979614
  (0, 3762)	0.20359578843763718
  (0, 20589)	0.20359578843763718
  (0, 3163)	0.14259780524993432
  (0, 13395)	0.1233463491185213
  (0, 12874)	0.13185659359055446
  (0, 2444)	0.10781958477021607
  (0, 10647)	0.09214309192267582
  (0, 14977)	0.09260727804816758
  (0, 9237)	0.10489811783749833
  (0, 31595)	0.10688588151431454
  :	:
  (4802, 12885)	0.2407245731353637
  (4802, 17113)	0.4814491462707274
  (4802, 4900)	0.2407245731353637
  (4802, 4899)	0.2407245731353637
  (4802, 12152)	0.2407245731353637
  (4802

# **Cosine Similirity**

In [ ]:
similirity = cosine_similarity(feature_vectors)

In [ ]:
print(similirity)

[[1.         0.06916756 0.03161679 ... 0.02202353 0.         0.02131466]
 [0.06916756 1.         0.03883524 ... 0.02174559 0.         0.01273336]
 [0.03161679 0.03883524 1.         ... 0.01366349 0.0250206  0.01067866]
 ...
 [0.02202353 0.02174559 0.01366349 ... 1.         0.         0.0320506 ]
 [0.         0.         0.0250206  ... 0.         1.         0.        ]
 [0.02131466 0.01273336 0.01067866 ... 0.0320506  0.         1.        ]]


In [ ]:
similirity.shape

(4803, 4803)

In [ ]:
movie_name = input("enter your favourite movie name-")

enter your favourite movie name-iron man


In [ ]:
# creating the list of simillar movies from the dataset
movie_titles = movies['title'].tolist()
print(movie_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
#finding the close match
close_match = difflib.get_close_matches(movie_name , movie_titles)
print(close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [ ]:
closest_match = close_match[0]
print(closest_match)

Iron Man


In [ ]:
#find the index of the movie
index_of_movie = movies[movies.title == closest_match]['index'].values[0]
print(index_of_movie)

68


In [ ]:
similirity_score = list(enumerate(similirity[index_of_movie]))
print(similirity_score)
len(similirity_score)

[(0, 0.018826856226963472), (1, 0.03263190702851822), (2, 0.010273452038390902), (3, 0.012472764859583488), (4, 0.01568915437044787), (5, 0.062343854125715616), (6, 0.035536250431523024), (7, 0.2545684260393275), (8, 0.003896420681986396), (9, 0.05456954542053657), (10, 0.04627687151751481), (11, 0.006764127894332359), (12, 0.005298716122089283), (13, 0.012416730792707935), (14, 0.06524245144360351), (15, 0.02002444606578528), (16, 0.3169658771274837), (17, 0.009715831110321583), (18, 0.017874196437775842), (19, 0.011384157899474716), (20, 0.12987743590963763), (21, 0.01093401272127972), (22, 0.006556887562505373), (23, 0.006007814776176503), (24, 0.006374899657938001), (25, 0.005433078921238392), (26, 0.25200044426163937), (27, 0.01744996640821945), (28, 0.06652791636545088), (29, 0.007788876653979954), (30, 0.13339385007488885), (31, 0.34810266331806045), (32, 0.023235959116696656), (33, 0.13015685470394112), (34, 0.01762907337244956), (35, 0.05347376039413568), (36, 0.04938068215933

4803

In [ ]:
similirity_score = sorted(similirity_score , key = lambda x:x[1], reverse = True)
print(similirity_score)

[(68, 1.0000000000000002), (31, 0.34810266331806045), (79, 0.3210180380554079), (16, 0.3169658771274837), (85, 0.2556454817008016), (7, 0.2545684260393275), (26, 0.25200044426163937), (174, 0.21593580249755415), (182, 0.21014205514428547), (169, 0.19632071840143414), (129, 0.1867434440253135), (126, 0.18582024635498845), (511, 0.16795815394491856), (64, 0.16425363914570554), (203, 0.16356045650406137), (46, 0.16180429693789622), (788, 0.1608593517140749), (101, 0.14819783596289182), (4401, 0.14449461515320955), (38, 0.143706130201731), (94, 0.14282856842451558), (805, 0.14101687928894052), (30, 0.13339385007488885), (232, 0.13072277782904115), (33, 0.13015685470394112), (20, 0.12987743590963763), (242, 0.1265744858747877), (122, 0.12384532901940479), (1740, 0.1144134599362463), (954, 0.1075462957442579), (353, 0.09579037672196135), (1210, 0.09207083832602497), (654, 0.09145476669842209), (2390, 0.09050720156746156), (1406, 0.08440036053754138), (3166, 0.08176759193727133), (1664, 0.081

In [ ]:
#printing the names of similar movies
movies = pd.read_csv('/content/movies.csv')
print('Movies suggested for you: \n')
i = 1
for movie in similirity_score:
  index = movie[0]
  title_from_index = movies[movies.index == index]['title'].values[0]
  if i<11:
    print(i,":",title_from_index,"\n")
    i+=1

Movies suggested for you: 

1 : Iron Man 

2 : Iron Man 3 

3 : Iron Man 2 

4 : The Avengers 

5 : Captain America: The Winter Soldier 

6 : Avengers: Age of Ultron 

7 : Captain America: Civil War 

8 : The Incredible Hulk 

9 : Ant-Man 

10 : Captain America: The First Avenger 



# **Final Recommendation System**

In [ ]:
movie_name = input("enter your favourite movie name-")
movie_titles = movies['title'].tolist()
close_match = difflib.get_close_matches(movie_name , movie_titles)
closest_match = close_match[0]
index_of_movie = movies[movies.title == closest_match]['index'].values[0]
similirity_score = list(enumerate(similirity[index_of_movie]))
similirity_score = sorted(similirity_score , key = lambda x:x[1], reverse = True)

movies = pd.read_csv('/content/movies.csv')
print('Movies suggested for you: \n')
i = 1
for movie in similirity_score:
  index = movie[0]
  title_from_index = movies[movies.index == index]['title'].values[0]
  if i<11:
    print(i,":",title_from_index,"\n")
    i+=1

enter your favourite movie name-avatar
Movies suggested for you: 

1 : Avatar 

2 : Rise of the Planet of the Apes 

3 : X-Men: First Class 

4 : Dragonball Evolution 

5 : The Watch 

6 : Alien 

7 : Eragon 

8 : Fantastic 4: Rise of the Silver Surfer 

9 : Live Free or Die Hard 

10 : X-Men Origins: Wolverine 

